---
title: "Project"
author: "Mohammed Hussain"
date: "2025-12-18"
output: 
  html_document:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE, error=FALSE}
library(readxl)
library(tidyverse)
library(sf)
library(plotly)
```


```{r region data}

region_df <- read_csv("C:/Users/amaan/Desktop/Project/2023 Infant Death Rates (per 1,000 live births) by Region-County.csv", skip = 4, col_names = TRUE)

region <- 
  region_df |>
  select("Residence:","2023 Infant Deaths","2023 Rate","2023 C.I.",
         "Percent Change 2022 - 2023") |>
  mutate(across(everything(), ~ str_remove_all(.x, "\\*"))) |>
  separate(
    "2023 C.I.", into = c("Lower_C.I,","Upper_C.I."), sep = " - "
    ) |>
  mutate(across(-1, as.numeric)) |>
      rename(
    "Residence" = "Residence:",
    "Deaths" = "2023 Infant Deaths",
    "Rate" = "2023 Rate",
    "Pct_Change_2022-23" = "Percent Change 2022 - 2023"
  ) |>
  slice(1:(n() - 3))

northeastern <- c("Caswell","Person","Granville","Vance","Warren","Alamance","Orange","Durham","Franklin","Chatham","Wake","Lee","Johnston")
  
```

```{r region map}

nc_shp_file <- system.file("shape/nc.shp", package = "sf")
nc_shp <- st_read(nc_shp_file, quiet = TRUE)

nc_region <- 
  nc_shp |>
  mutate(NAME = str_to_upper(NAME)) |>
  left_join(region, by = c("NAME" = "Residence"))

g <- ggplot(nc_region) +
  geom_sf(aes(fill = Rate)) +
  scale_fill_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(fill = "Infant Death Rate")
ggplotly(g)

```

